# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 18:47
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('belt2', '0002_auto_20160831_1127'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tasks',
            managers=[
                ('taskmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
